/**
 * Authentication error codes for standardized error responses
 */
export const AUTH_ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  REFRESH_EXPIRED: 'REFRESH_EXPIRED',
  REFRESH_REVOKED: 'REFRESH_REVOKED',
  REFRESH_INVALID: 'REFRESH_INVALID',
  REFRESH_FAILED: 'REFRESH_FAILED',
  USER_INACTIVE: 'USER_INACTIVE',
  EMAIL_VERIFICATION_REQUIRED: 'EMAIL_VERIFICATION_REQUIRED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
} as const;
